package com.mitch.ktlint_test

import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.*
import androidx.appcompat.app.AppCompatActivity

class MainActivity(val testOne: Int, val testTwo: Int, val testThree: Int, val testFive: Int, val testFour: Int) : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        (savedInstanceState?.let { Log.d("TEST", "Test") })?.let { }

        val test =
            "1q234"
    }

    fun testFunction() {
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
        Log.d("TAG", "TEST")
    }
}
